version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sih
      MYSQL_USER: sih
      MYSQL_PASSWORD: sih
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: mysql+pymysql://sih:sih@db:3306/sih
      CORS_ORIGINS: http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    ports:
      - "4173:4173"

volumes:
  db_data:
